/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ispot_tunity_core_opus_AndroidOpusDecoder */

#ifndef _Included_com_ispot_tunity_core_opus_AndroidOpusDecoder
#define _Included_com_ispot_tunity_core_opus_AndroidOpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ispot_tunity_core_opus_AndroidOpusDecoder
 * Method:    decoderCreate
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_ispot_tunity_core_opus_AndroidOpusDecoder_decoderCreate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ispot_tunity_core_opus_AndroidOpusDecoder
 * Method:    decode
 * Signature: (J[B[SII)I
 */
JNIEXPORT jint JNICALL Java_com_ispot_tunity_core_opus_AndroidOpusDecoder_decode
  (JNIEnv *, jobject, jlong, jbyteArray, jshortArray, jint, jint);

/*
 * Class:     com_ispot_tunity_core_opus_AndroidOpusDecoder
 * Method:    decoderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ispot_tunity_core_opus_AndroidOpusDecoder_decoderDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
